<a href="https://colab.research.google.com/github/erenakgunduz/Probability_Statistics/blob/main/ErenAkgunduz_Lab_3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Stats Lab #3
## Eren Akgunduz

In [1]:
import numpy as np
from IPython.core.display import display, HTML

### Loops

In [2]:
# Iterating through ranges using for loops
for i in range(100):
    print(i)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44
45
46
47
48
49
50
51
52
53
54
55
56
57
58
59
60
61
62
63
64
65
66
67
68
69
70
71
72
73
74
75
76
77
78
79
80
81
82
83
84
85
86
87
88
89
90
91
92
93
94
95
96
97
98
99


In [3]:
for i in range(5,8):
    print(i)

5
6
7


In [4]:
for i in range(3):
    print(f"Test number: {i}")

Test number: 0
Test number: 1
Test number: 2


### Functions

In [5]:
# The function definition in Python, with the def keyword and parantheses containing optional parameters
# Interpreter will "return" whatever you specify in your function's code,
# depending on which return statement runs and what its code is, each time the function is called
# A function will normally NOT execute any code after it returns, so you can't write any right after it (there are ways of going around this though)
def square(x):
    return x**2

In [6]:
# Calling the square function, the values you pass into a function are your arguments
# They will set the values of the function's parameters (defined when you first create one) to whatever you specify in a particular call
square(5)

25

In [7]:
# Nesting a call to square INSIDE a call to square as the outer call's argument
square(square(2))

16

In [8]:
# Another level of nesting, so this process can be described as 2**2->4, 4**2->16, 
# and then the outermost cal1 once the inner ones are computed -- 6**2->256
square(square(square(2)))

256

In [9]:
# Works for larger numbers too, of course
square(123456)

15241383936

In [10]:
# Another example
square(square(5))

625

In [11]:
# Now here's a numpy array with some duplicate values
squares = np.array([0, 1, 3, 3, 2, 4, 5, 5, 6])
squares_sorted = np.sort(squares) # put these values in numerical order
print(f"{squares}\n{squares_sorted}")

[0 1 3 3 2 4 5 5 6]
[0 1 2 3 3 4 5 5 6]


In [12]:
# We use an anonymous function to define a function on just one line and then put it to use on that same line
# In this case, "mapping" (using a function to assign new values to a list based on the function's code) the values to their squared values
# Then I turn it into a set, which is a data type (also built into Python) that is unordered and unindexed
# So, you can't change existing items using an index, but you can add and remove items
# Sets also only store unique values, so NO duplicates
squares = np.array(list(map(lambda x: x**2, squares_sorted)))
print(squares, squares.shape)
squares = set(squares)
print(squares, len(squares))

[ 0  1  4  9  9 16 25 25 36] (9,)
{0, 1, 4, 36, 9, 16, 25} 7


In [13]:
# As you can see
print(squares_sorted, squares)

[0 1 2 3 3 4 5 5 6] {0, 1, 4, 36, 9, 16, 25}


In [14]:
# Another simple function, one parameter (the number to add two to, x), returns x + 2 of course
def add_two(x):
    return x+2

In [15]:
add_two(5)

7

In [16]:
# Combining the two functions we've defined already, 5+2=7 so the square call sees square(7) which is 49
square(add_two(5))

49

In [17]:
# The same exact thing as above, but now add_two's functionality (because it's really simple) is achieved
# using an anonymous function, which is then immediately "invoked" (called with a value) using the IIFE syntax of Python
square((lambda x: x + 2)(5))

49

In [18]:
# Taking it a step further, though most of the time it really makes life easier for the human if you just use named functions
# This is just a neat feature :)
(lambda x: x**2)((lambda x: x + 2)(5))

49

### Logical Branching

In [19]:
choice = "apple"

In [20]:
# Run through each condition one at a time and keep going only if none have been met yet
# As soon as a condition IS satisfied (the expression is boolean True), execute the code inside that block only
if choice == "apple":

    print("You choose apples.")

else:
    
    print("You did not choose apples.")

You choose apples.


In [21]:
choice = "orange"

In [22]:
choice = "apple"

In [23]:
# Begin with "if", then any specific other conditions in the order you want to check them with "elif" (else if)
# anything else (none of the previous conditions YOU specified were met) with "else"
if choice == "apple":

    print("You choose apples.")
    print("Thank you, shop again!")
    print(2**123)

elif choice == "orange":

    print("You choose oranges.")
    print("Thank you, shop again!")

else:
    
    print("You did not choose apples or oranges.")
    print("Thank you, shop again!")

You choose apples.
Thank you, shop again!
10633823966279326983230456482242756608


### User Input

In [24]:
# Using the input() method to take the user's input
choice = input("Please enter your choice (i.e. apple): ")

Please enter your choice (i.e. apple): oranges


In [25]:
choice

'oranges'

In [26]:
if choice == "apple":

    print("You choose apples.")

elif choice == "oranges":

    print("You choose oranges.")

else:
    
    print("You did not choose apples or oranges.")

You choose oranges.


#### Coins

In [27]:
# Code for the following few sections (coins, graphics output, coin flip) I already annotated in my Lab 2 notebook
# https://github.com/erenakgunduz/Probability_Statistics/blob/main/ErenAkgunduz_Lab_2.ipynb
np.random.random()

0.216132065760956

In [28]:
np.random.random() > 0.5

False

In [29]:
def flip_coin():
    if np.random.random() > 0.5:
        print("Heads")
    else:
        print("Tails")

In [30]:
flip_coin()

Tails


### Graphics Output

In [31]:
display(HTML('<h1>Hello, world!</h1>'))

In [32]:
def coin():
  return np.random.randint(2)

In [33]:
coin()

0

In [34]:
display(HTML('<img src="https://random-ize.com/coin-flip/us-quarter/us-quarter-front.jpg">'))

In [35]:
heads = 'https://random-ize.com/coin-flip/us-quarter/us-quarter-front.jpg'
tails = 'https://random-ize.com/coin-flip/us-quarter/us-quarter-back.jpg'

In [36]:
def show_img(img):
  display(HTML('<img src=' + img + '>'))

In [37]:
show_img(heads)

In [38]:
show_img(tails)

In [39]:
def flip_coin():

    if coin():
        show_img(heads)
    else:
        show_img(tails)

In [40]:
flip_coin()

In [41]:
for i in range(5):
    flip_coin()

In [42]:
#@title Coin Flip

if coin():

  show_img(heads)

else:

  show_img(tails)

### Cards

In [43]:
def shuffle(x):
    # Start value is the size (length) of the "deck of cards" - 1, because the full size won't be a valid index
    # Stop at zero, but we're iterating in REVERSE because the step size is -1 instead of the default of 1 (positive one)
    for i in range(len(x)-1,0,-1):
        # The new value will be any random integer between 0 and i, i included (so i+1 because the stop value is excluded here)
        j = np.random.randint(0,i+1)
        # "Shuffle" the deck - just take the existing order, then swap it out
        x[i],x[j] = x[j],x[i]
        # print(j,x)
    return x

In [44]:
# Constructing the deck of cards (contains 52 integers, 0-51)
a = np.arange(52)

In [45]:
# Pass in the cards to the shuffle function
shuffle(a)

array([48, 24, 33, 17, 18, 13, 45, 41, 43, 25, 49, 15, 19,  2, 51, 14, 10,
       23, 47, 29, 42,  9, 28,  7, 12, 26, 44,  1, 40, 30, 11, 46,  3, 20,
       37,  0,  8, 36,  5, 21, 38, 16, 35, 50, 22, 31,  4,  6, 32, 39, 27,
       34])

In [46]:
# Same result as all the above using numpy's built-in permutation() method
# For a situation like this, this is the better option because it's less code and also faster
np.random.permutation(52)

array([31, 35,  3, 23, 50, 49,  7, 24, 37,  2, 43,  4, 28, 14, 25, 13, 15,
       46,  9, 22, 39, 41, 26, 12, 27, 21, 45,  6, 40, 17, 10, 16, 32, 30,
       20, 36,  0, 42, 29, 44,  1,  8, 19, 34, 18, 11, 47, 33, 38, 48, 51,
        5])

### Speed Test

In [47]:
%%timeit
shuffle(a)

371 µs ± 49.9 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [48]:
%%timeit
np.random.permutation(52)

3.58 µs ± 195 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [49]:
# As we can see above ^^, but still it's always good to look at different ways to approach a problem
np.random.permutation(52)

array([32, 38,  0, 42, 49,  8,  4, 33, 20, 12, 15, 22, 27, 36, 13, 48, 40,
       14,  9, 46, 39, 29, 45, 17, 18, 44, 26,  6, 31, 16, 30, 19, 35, 37,
       21, 24, 23,  3, 25, 34, 50,  5, 11,  2, 43,  1,  7, 41, 47, 28, 51,
       10])

In [50]:
# Create a representation of a shuffled deck of cards
cards = np.random.permutation(52)

In [51]:
# Here it is
cards

array([41, 35, 17,  6, 30, 42,  7, 40, 43, 27, 44, 45, 14, 18, 48, 16, 33,
       46, 32, 39, 21, 11, 49, 25, 29, 51,  3,  5,  2, 34, 36,  1, 13,  8,
       12, 10, 23, 37,  0, 50, 20, 22,  4, 38, 28, 24,  9, 31, 26, 47, 19,
       15])

In [52]:
# Get the card's numerical representation by its index (where it can be found in the "deck")
cards[0]

41

In [53]:
cards[1]

35

In [54]:
cards[2]

17

<!-- Here's the image with all the cards in a playing card deck -->
<img src='http://www.milefoot.com/math/discrete/counting/images/cards.png'>

In [55]:
# Reshape our array into a new one divided into four smaller arrays, each with 13 items (4*13=52)
print(np.arange(52).reshape(4,13), "\n")
# Could also think of it as turning the simple vector (from arange) into a matrix with the shape of our choice
print(np.arange(52).shape)  # what was the shape before?
print(np.arange(52).reshape(4,13).shape)  # what's the shape now?

[[ 0  1  2  3  4  5  6  7  8  9 10 11 12]
 [13 14 15 16 17 18 19 20 21 22 23 24 25]
 [26 27 28 29 30 31 32 33 34 35 36 37 38]
 [39 40 41 42 43 44 45 46 47 48 49 50 51]] 

(52,)
(4, 13)


In [56]:
# Apply the modulo operation to the whole array
# Gives an array with all the remainders of the division of our original values and 13
np.arange(52).reshape(4,13) % 13

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
       [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
       [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
       [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12]])

In [57]:
# Apply long division to the array with //, now we don't want the remainder, just the long division, and it looks like this
np.arange(52).reshape(4,13) // 13

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2],
       [3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3]])

In [58]:
# Defining our lists of possible suits and cards
suits = ['Clubs','Spades','Hearts','Diamonds']
names = ['Ace','Two','Three','Four','Five','Six','Seven','Eight','Nine','Ten','Jack','Queen','King']

In [59]:
def card_name(card_number):
    "Translate the number representation to the actual card name in human language"
    suit = card_number//13  # For the suit you can see why we'd want to use long division
    name = card_number%13  # As for the actual card, we can also see above why modulo is perfect

    # Return the card name, which we're able to do by getting the exact item from the list with the index we figure out above
    # The indices map to the suits and names, they're in the order we want for this
    return f"{names[name]} of {suits[suit]}"

In [60]:
# there we go
card_name(0)

'Ace of Clubs'

In [61]:
card_name(51)

'King of Diamonds'

In [62]:
# We did this before, let's do it again
cards = np.random.permutation(52)

In [63]:
# Assigning some variables to the card names at those locations in the deck, which we get with the index
top_of_deck         = card_name(cards[0])
second_card_in_deck = card_name(cards[1])
last_card_in_deck   = card_name(cards[-1])

In [64]:
top_of_deck, second_card_in_deck, last_card_in_deck

('Five of Spades', 'King of Diamonds', 'Four of Clubs')

In [65]:
# Get the names of the first five cards in the deck (imagine this as starting from the top)
for i in range(5):
    print(card_name(cards[i]))

Five of Spades
King of Diamonds
Three of Clubs
Four of Hearts
Three of Spades


In [66]:
# First 15 cards
for i in range(15):
    print(card_name(cards[i]))

Five of Spades
King of Diamonds
Three of Clubs
Four of Hearts
Three of Spades
Six of Diamonds
Ten of Hearts
King of Spades
Ace of Hearts
Jack of Clubs
Five of Clubs
Two of Clubs
Two of Diamonds
Eight of Spades
Five of Diamonds


https://www.improvemagic.com/all-playing-cards-names-with-pictures/

In [67]:
# Going to do some link manipulation now, so these variables are going to be exactly like this
card_url_head = "https://www.improvemagic.com/wp-content/uploads/2020/11/"
card_url_tail = ".png"

In [68]:
suit = ['k','p','s','l']  # here as well
card = ['a','2','3','4','5','6','7','8','9','10','j','q','k']

In [69]:
# The system for getting a random suit and card
i = np.random.randint(4)
j = np.random.randint(13)

In [70]:
i,j

(3, 0)

In [71]:
suit[i]

'l'

In [72]:
card[j]

'a'

In [73]:
def show_img(img):
  display(HTML(f"<img src={img} />")) # the parameter is what we use for the image source (the link to it)

In [74]:
# Putting it all together looks like this
img = card_url_head + suit[i] + card[j] + card_url_tail

In [75]:
print(img)
show_img(img)  # seems to work!

https://www.improvemagic.com/wp-content/uploads/2020/11/la.png


In [76]:
# Placing what we had above into a function
def card_image(card_number):
    
    i = card_number//13
    j = card_number%13

    return suit[i]+card[j]

In [77]:
# The component we'll need for the image URL (the img variable)
card_image(3)

'k4'

In [78]:
# Same thing as before but now incorporating the card_image() function
img = card_url_head + card_image(3) + card_url_tail

In [79]:
# The card with index 3 should be the Four of Clubs, which this displays
show_img(img)

In [80]:
# Now show me all of them >:)
for i in range(52):
    img = card_url_head + card_image(i) + card_url_tail
    show_img(img)